### ISSUE TITLE
Область видимости игрока

### ISSUE THREAD

**Issue by SoCoL-** [SoCoL-/Sleeper#25]
Сделать туман войны. Сделать область видимости игрока. Ограничение стенами и дверьми видимости.

**Comment by engor** [comment]
Есть участки - со всех сторон закрытые стенами, там туман войны никак не убирается, получается обошёл вокруг такую область, а внутри чернота. Может надо убирать там туман.

**Comment by SoCoL-** [comment]
Можешь зафотать этот кусок и показать. Я догадываюсь, о чем ты, но хотелось бы убедиться)

**Comment by engor** [comment]
![2013-11-01-17-42-22 1](https://f.cloud.github.com/assets/5233803/1452651/1b5fcc34-42da-11e3-8805-dc700acc1f70.png)
Обошёл вокруг непроходимого куска, он чёрный так и остался. не знаю нужно ли убирать туман, но можно бы.

**Comment by SoCoL-** [comment]
Ага, все понял тебя. Тут вообще ничего нет на самом деле. Тоесть невидимая часть для игрока, думал над тем, чтобы ставить "крышу", но пока решил оставить как есть.

**Comment by SoCoL-** [comment]
http://roguebasin.roguelikedevelopment.org/index.php?title=Field_of_Vision
http://roguebasin.roguelikedevelopment.org/index.php?title=Extremely_fast_simplified_LOS

**Comment by SoCoL-** [comment]
http://roguebasin.roguelikedevelopment.org/index.php?title=Simple_and_accurate_LOS_function_for_BlitzMax

**Comment by SoCoL-** [comment]
http://roguebasin.roguelikedevelopment.org/index.php?title=LOS_by_Odd

**Comment by SoCoL-** [comment]
готово! =)

**Comment by SoCoL-** [comment]
Все печально, случайно удалил(
