### ISSUE TITLE
"Продолжить" из меню, не снимает паузу.

### ISSUE THREAD

**Issue by sibcrash** [SoCoL-/Sleeper#53]
Нажимаю кнопку назад, вылазит меню, нажимаю "Продолжить" - ходить не дает. 

Если из меню выйти кнопкой назад, то ходить дает. Похоже, что "Продолжить" не снимает паузу с игры.

**Comment by SoCoL-** [comment]
После закрытия меню не снимал игру с паузы. Поправил
